name: tbis_tv
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: LatoRegular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: LatoMedium
      fonts:
        - asset: assets/fonts/Lato-Medium.ttf
    - family: LatoSemiBold
      fonts:
        - asset: assets/fonts/Lato-SemiBold.ttf
