name: tbis_tv
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  intl: ^0.19.0
  dio: ^5.4.0
  logger: ^2.0.2+1
  synchronized: ^3.1.0+1
  http_parser: ^4.0.2
  encrypt: ^5.0.3
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10
  fl_chart: ^0.68.0
  provider: ^6.1.2
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  shared_preferences: ^2.2.2
  dropdown_button2: ^2.3.9
  flutter_layout_grid: ^2.0.7
  auto_height_grid_view: ^1.0.0
  json_table: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: LatoRegular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: LatoMedium
      fonts:
        - asset: assets/fonts/Lato-Medium.ttf
    - family: LatoSemiBold
      fonts:
        - asset: assets/fonts/Lato-SemiBold.ttf